install.packages("readxl")
library(readxl)
library('weathercan')
library('sf')
library('leaflet')
library('reshape2')
library('ggplot2')

# Set the working directory (location where lab_4_incomplete.R and associated data are available)
# Pay attention to forward slash /
setwd('C:/Users/14037/OneDrive - University of Calgary/Documents/ENCI_570/TM_PHES_code/TM_PHES')

# Read the shapefile of the watershed boundary using st_read()
basin <- st_read('shapefile.shp')

# Select the actual boundary (correct feature) as the rest are errors generated by the delineation algorithm
basin <- basin[2,]

# Reproject the layer to WGS 84 since weather gauges coordinates are in WGS 84.
# Use st_transform with crs=4326 as parameter. 4326 is the EPSG code of WGS 84 CRS
basin <- st_transform(basin, crs = 4326) #4326 is the EPSG code of WGS 84 CRS

# Get basin centroid coordinates to search for nearby weather stations
basin_centroid <- st_coordinates(st_centroid(basin))

# If you face an error because the geometry is not valid, you need to make it valid
# use st_make_valid()
basin <- st_make_valid(basin)

#Get basin centroid for the valid geometry
basin_centroid <- st_coordinates(st_centroid(basin))

# Specify the path to your Excel file
excel_file_path <- "C:/Users/14037/OneDrive - University of Calgary/Documents/ENCI_570/TM_PHES_code/gauge_location_raw.xlsx"

# Read the Excel file into a data frame
excel_data <- read_excel(excel_file_path)

# View the contents of the data frame
print(excel_data)


# Function to convert DMS to decimal degrees
dms_to_dd <- function(dms) {
  degrees <- as.numeric(substring(dms, 1, regexpr("[°]", dms) - 1))
  minutes <- as.numeric(substring(dms, regexpr("[°]", dms) + 1, regexpr("'", dms) - 1))
  seconds <- as.numeric(substring(dms, regexpr("'", dms) + 1, regexpr("\"", dms) - 1))
  direction <- substring(dms, nchar(dms), nchar(dms))
  
  dd <- degrees + minutes/60 + seconds/3600
  dd[direction %in% c("S", "W")] <- -abs(dd[direction %in% c("S", "W")])
  
  return(dd)
}

# Convert DMS to decimal degrees for latitude
excel_data$lat_dd <- dms_to_dd(excel_data$lat)
# Convert DMS to decimal degrees for longitude
excel_data$lon_dd <- dms_to_dd(excel_data$lon)

print(excel_data)
######################
# Visualize the watershed and available points
# Convert avail_stn to sf (shapefile) object to be plotted 
# Use st_as_sf() with the following parameters: coords = c('lon', 'lat'), crs= 4326
avail_stn_shp <- st_as_sf(excel_data, coords = c('lon_dd', 'lat_dd'), crs= 4326)
# Convert basin to a data frame for plotting
basin_df <- st_as_sf(basin, crs = 4326) %>% st_sf()

#plotting an interactive map
leaflet() %>% # this operator (%>%) is called pipe, which means then
  addTiles() %>% #load background image
  addCircleMarkers(data = avail_stn_shp, label = ~gstation_name,
                   labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE)) %>%
  addPolygons(data = basin, color = 'red')


# Download the data for the required stations
#weather_data <- weather_dl(station_ids = avail_stn$station_id, interval = 'day')

# Save weather_data as a CSV file
write.csv(excel_data, "gauge_data.csv", row.names = FALSE)
