## install the required packages. This needs to be done the first time you run the script
## weathercan is the package that retrieves the data from the Meteorological Service of Canada
## database https://climate.weather.gc.ca/historical_data/search_historic_data_e.html
install.packages("weathercan", repos = c("https://ropensci.r-universe.dev", "https://cloud.r-project.org"))
## sf package works with vector data
# install.packages('sf')
## leaflet package produces interactive spatial maps
# install.packages('leaflet')
## reshape2 is a package used to preprocess data frames
# install.packages('reshape2')
## ggplot2 makes nice figures
# install.packages('ggplot2')
## load the required packages
library('weathercan')
library('sf')
library('leaflet')
library('reshape2')
library('ggplot2')

# Set the working directory (location where lab_4_incomplete.R and associated data are available)
# Pay attention to forward slash /
setwd('C:/Users/14037/OneDrive - University of Calgary/Documents/ENCI_570/TM_PHES_code/TM_PHES')

# Read the shapefile of the watershed boundary using st_read()
basin <- st_read('shapefile.shp')

# Select the actual boundary (correct feature) as the rest are errors generated by the delineation algorithm
basin <- basin[2,]

# Reproject the layer to WGS 84 since weather gauges coordinates are in WGS 84.
# Use st_transform with crs=4326 as parameter. 4326 is the EPSG code of WGS 84 CRS
basin <- st_transform(basin, crs = 4326) #4326 is the EPSG code of WGS 84 CRS

# Get basin centroid coordinates to search for nearby weather stations
basin_centroid <- st_coordinates(st_centroid(basin))

# If you face an error because the geometry is not valid, you need to make it valid
# use st_make_valid()
basin <- st_make_valid(basin)

#Get basin centroid for the valid geometry
basin_centroid <- st_coordinates(st_centroid(basin))

# Search for nearby weather stations that has daily data
avail_stn <- stations_search(coords = rev(basin_centroid), # the function needs lat then lon
                             interval = 'day',  
                             dist = 25) # searches by last year of record, location, and distance
print(avail_stn)
######################
# Visualize the watershed and available points
# Convert avail_stn to sf (shapefile) object to be plotted 
# Use st_as_sf() with the following parameters: coords = c('lon', 'lat'), crs= 4326
avail_stn_shp <- st_as_sf(avail_stn, coords = c('lon', 'lat'), crs= 4326)
# Convert basin to a data frame for plotting
basin_df <- st_as_sf(basin, crs = 4326) %>% st_sf()

#plotting an interactive map
leaflet() %>% # this operator (%>%) is called pipe, which means then
  addTiles() %>% #load background image
  addCircleMarkers(data = avail_stn_shp, label = ~station_name,
                   labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE)) %>%
  addPolygons(data = basin, color = 'red')


# Download the data for the required stations
weather_data <- weather_dl(station_ids = avail_stn$station_id, interval = 'day')

# Save weather_data as a CSV file
write.csv(weather_data, "weathercan_data.csv", row.names = FALSE)
